# Generated by Django 6.1 on 2026-08-21 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('headline', models.CharField(max_length=150, verbose_name='Titular / Profesión')),
                ('bio', models.TextField(verbose_name='Biografía / Sobre Mí')),
                ('avatar_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL Foto de Perfil')),
                ('cv_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL del CV (PDF)')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Perfil Activo?')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50, verbose_name='Plataforma (Ej: LinkedIn)')),
                ('url', models.URLField(max_length=255, verbose_name='Enlace Red Social')),
                ('icon_name', models.CharField(max_length=50, verbose_name='Nombre Icono')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
            },
        ),
    ]
