# Generated by Django 6.1 on 2026-08-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_avatar_url_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_3d',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
