services:
  db:
    image: mysql:8.0
    container_name: portafolio-db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_HOST: "%"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - red_portafolio

  backend:
    build: .
    container_name: portafolio-backend
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - red_portafolio

  frontend:
    build: ./frontend
    container_name: portafolio-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - red_portafolio

networks:
  red_portafolio:
    driver: bridge

volumes:
  db_data: