services:
  db:
    image: mysql:8.0
    container_name: portafolio-db
    restart: always
    environment:
      MYSQL_DATABASE: portfolio_db
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: "%"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: portafolio-backend
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: portafolio-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data: