version: '3.8'

services:
  backend:
    build: .
    container_name: portafolio-backend
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: portafolio-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend