# Generated by Django 6.1 on 2026-08-21 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre Categoría')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (URL)')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tecnología (Ej: Django, Vue 3)')),
                ('icon_slug', models.CharField(max_length=50, verbose_name='Identificador Icono')),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Tecnologías',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título del Proyecto')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('summary', models.TextField(verbose_name='Resumen Corto')),
                ('description', models.TextField(verbose_name='Descripción Detallada')),
                ('cover_image', models.URLField(max_length=255, verbose_name='URL Imagen Portada')),
                ('featured', models.BooleanField(default=False, verbose_name='¿Proyecto Destacado?')),
                ('project_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Enlace Demo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portafolio.category', verbose_name='Categoría')),
                ('technologies', models.ManyToManyField(related_name='projects', to='portafolio.projecttechnology', verbose_name='Tecnologías Usadas')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=255, verbose_name='URL Imagen Galería')),
                ('caption', models.CharField(blank=True, max_length=150, null=True, verbose_name='Pie de Foto')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('aspect_ratio', models.CharField(default='landscape', max_length=20, verbose_name='Relación Aspecto')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_gallery', to='portafolio.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Galería del Proyecto',
                'verbose_name_plural': 'Galerías de Proyectos',
                'ordering': ['display_order'],
            },
        ),
    ]
