# Generated by Django 6.1 on 2026-08-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_remove_project_cover_image_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avatar_3d',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
