# Generated by Django 6.1 on 2026-08-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Clave Única (Ej: hero_logo)')),
                ('title', models.CharField(max_length=100, verbose_name='Título del Recurso')),
                ('asset_url', models.URLField(max_length=255, verbose_name='URL del Recurso / Imagen')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción Corta')),
            ],
            options={
                'verbose_name': 'Recurso del Sitio',
                'verbose_name_plural': 'Recursos del Sitio',
            },
        ),
    ]
