# Generated by Django 6.1 on 2026-08-21 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título del Dataset')),
                ('total_respondents', models.IntegerField(default=0, verbose_name='Total Encuestados')),
                ('description', models.TextField(verbose_name='Descripción / Metodología')),
                ('cv_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL Documentación Extra')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Dataset Activo?')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bi_datasets', to='portafolio.project', verbose_name='Proyecto Asociado')),
            ],
            options={
                'verbose_name': 'Dataset de BI',
                'verbose_name_plural': 'Datasets de BI',
            },
        ),
        migrations.CreateModel(
            name='BiMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, verbose_name='Nombre del Grupo (Ej: Asignatura Preferida)')),
                ('label', models.CharField(max_length=100, verbose_name='Etiqueta (Ej: Matemáticas)')),
                ('numeric_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Numérico / Porcentaje')),
                ('filter_tag', models.CharField(blank=True, max_length=50, null=True, verbose_name='Filtro (Ej: 7mo Basico)')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analytics.bidataset', verbose_name='Dataset')),
            ],
            options={
                'verbose_name': 'Métrica de BI',
                'verbose_name_plural': 'Métricas de BI',
            },
        ),
    ]
